Feat/handle external integrations
Jozwiaczek/smart-gate pull request #489
Opened 2021-08-05 00:30 UTC by Jozwiaczek

2021-08-11 20:07 UTC, Mefjus requested changes

2021-08-11 20:07 UTC, Mefjus commented on packages/api/src/modules/external-integrations/guards/external-integrations-auth.guard.ts
> +    if (!foundUser || authorization !== foundUser.externalIntegrationsToken) {
when you remove a token you set it to '' (empty string). What if  someone sends you an email with an empty token??? XD

2021-08-11 20:07 UTC, Mefjus commented on packages/api/src/modules/external-integrations/guards/external-integrations-auth.guard.ts
> +    const foundUser = await this.usersService.findOneByEmail(from);
please use try catch here

2021-08-11 20:07 UTC, Mefjus commented on packages/client/src/hooks/useExternalIntegrations.ts
> +    const enUrl = 'https://www.icloud.com/shortcuts/3648757aeaf541e58752307b915c14d2';
maybe config or env ?

2021-08-11 22:46 UTC, Mefjus approved these changes

2021-08-13 06:45 UTC, Vatras commented on packages/api/src/modules/auth/guards/roles.guard.ts
> +    const requiredRoles = this.reflector.getAllAndOverride<Role[]>(constants.roles_key, [
You could export each constant separately and use index.ts with `export * from './module-with-constant';`
This way you could import  ROLES_KEY directly from '../../../constants' (`import  {ROLES_KEY}  from '../../../constants'`), which would look better, and also uppercase for constants is preffered

2021-08-13 06:47 UTC, Vatras commented on packages/api/src/modules/auth/guards/roles.guard.ts
> +    const requiredRoles = this.reflector.getAllAndOverride<Role[]>(constants.roles_key, [
You could also create a separate file for every const, this is also a nice approach (while some people may argue)

2021-08-13 06:49 UTC, Vatras commented on packages/api/src/modules/external-integrations/external-integrations.service.ts
> +    return 'Successfully open';
Such copy is usually stored in some const

2021-08-13 06:51 UTC, Vatras commented on packages/api/src/modules/external-integrations/guards/external-integrations-auth.guard.ts
> +      const foundUser = await this.usersService.findOneByEmail(from);
Shouldnt you take email from token instead of from headers where anyone can put anything?

2021-08-13 06:59 UTC, Vatras commented on packages/api/src/utils/constants.ts
> +const roles_key = 'roles';
If you create js variable with underscore, make sure its uppercased const, otherwise it looks like C++ :P

2021-08-13 15:09 UTC, Jozwiaczek commented
@all-contributors please add @Vatras for review

2021-08-13 16:33 UTC, merged

2021-08-13 16:57 UTC, Jozwiaczek commented
:tada: This PR is included in version 1.12.0 :tada:

The release is available on [GitHub release](https://github.com/Jozwiaczek/smart-gate/releases/tag/v1.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: